# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('weight', models.CharField(max_length=100)),
                ('allergic', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
