# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='picDog',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
