# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20170501_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.CharField(choices=[('Small', 'Less than 15'), ('Big', 'More than 15')], max_length=100),
        ),
    ]
