# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0008_auto_20170502_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='owner',
        ),
        migrations.AddField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
