# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20170502_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner',
            new_name='dogOwner',
        ),
    ]
