# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20170502_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password2',
        ),
    ]
