# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20170502_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
