# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20170503_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
