# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_auto_20170504_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picDog',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
