# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_auto_20170505_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic',
        ),
        migrations.AddField(
            model_name='person',
            name='piPerson',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
