# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_auto_20170506_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='piPerson',
        ),
        migrations.AddField(
            model_name='person',
            name='picPerson',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
