# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_auto_20170506_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picDog',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picPerson',
            field=models.FileField(default='', upload_to='documentsPerson/'),
        ),
    ]
