# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_auto_20170506_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picPerson',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
