# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_auto_20170506_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picPerson',
        ),
    ]
