# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_auto_20170508_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='picture',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
