# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0030_review_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='wine',
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.Person'),
        ),
    ]
