# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_auto_20170509_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.Person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
