# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0033_auto_20170509_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
        migrations.AddField(
            model_name='review',
            name='picDR',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
